# This is a basic workflow that is manually triggered
name: Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
    # Trigger the workflow on push or pull request,
    # but only for the master branch
    push:
        branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy_application:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Runs a single command using the runners shell
            - name: Invoke deployment hook
              uses: distributhor/workflow-webhook@v2
              env:
                  webhook_url: "http://localhost:8001/api/webhook"
                  data: '{ "server": "15", "site": "https://password-component.vercel.app"}'
